on:
  push: { branches: [publish] }
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.token }} | docker login ghcr.io --username $ --password-stdin
      - run: DOCKER_BUILDKIT=1 docker build --pull --push --tag ghcr.io/${{ github.repository_owner }}/meteor-template .
